### PR TITLE
Add user flow for Iteration 2

### PR DESCRIPTION
**Pull request by gtvj**
Hi @AshTNA - could you have a look at the PDF flow I've added to represent iteration two and, if it seems accurate, merge this PR? Many thanks.

### CODE REVIEW

**Review by AshGDS — CHANGES_REQUESTED** [review]
Hi @gtvj,

Thanks for adding this user flow into the repo and in general adding a lot of useful information to the repo.

I've noticed in the diagram it says there is currently no way to remove a subcategory. Currently the subcategories are all `<a>` tags which use the `href` to modify the subcategory GET parameter. If a subcategory GET param is detected, a "None" subcategory link then appears which allows you to remove the subcategory:

image

(I guess a better approach to this would have been to create a form with checkboxes and a submit button!)

Would you be able to update the diagram to reflect that a subcategory can be removed? Thanks :+1:

**Comment by gtvj** [comment]
Thanks Ash - I'd missed the 'None'. Will update now.

**Comment by gtvj** [comment]
All done and pushed.

**Review by AshGDS — APPROVED** [review]
All good, thanks Gwyn :+1:

**Pull request merged**
